language: java
os: linux
dist: trusty

jdk:
  - openjdk8
  - oraclejdk8
  - openjdk11
  - openjdk14
  - openjdk-ea

jobs:
  allow_failures:
    - jdk: openjdk-ea
  fast_finish: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8229d26a4f90bcc6cd67
script: mvn test -Dsurefire.useFile=false
